<?php /** @var \RLTSquare\BestSeller\Block\Product\GridProduct $block */ ?>
<?php if ($block->isEnableDisable() && $block->getCurrentPagePath()): ?>
    <?php $collection = $block->getCollection();
    $list_product = $block->getListProduct();
    $iterator = 1;
    $image = 'category_page_grid';
    $pos = $list_product->getPositioned();
    $_helper = $block->getCatalogHelper();
    $config = $list_product->getWidgetCfg();
    $showCart = 1;
    $showCompare = 0;
    $showWishlist = 1;
    $showReview = 1;
    $viewMode = 'grid';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    ?>
    <?php if ($collection->getData()): ?>
       <div class="rokan-featuredproduct">
            <?php $iterator = 1; ?>
           
			<div class="rokan-product-heading rokan-featured-heading"><h2><?= __('Best Selling Products') ?></h2></div>
			<div class="row">	
            <!--<ol class="products list items product-items regular slider">-->
            <ul class="owl">
                <?php foreach ($collection->getData() as $data) { ?>
                    <?php $product_id = $data['product_id']; ?>
                    <?php $_product = $block->getLoadProduct($product_id); ?>
                    <?php if (isset($_product)): ?>
                        <?php if ($_product->getID()): ?>
                            <?php /* @escapeNotVerified */ ?>
                            <?php echo ($iterator++ == 1) ? '<li class="item featuredproductslider-item">' : '</li><li class="item featuredproductslider-item">' ?>
                            <div class="product-item" data-container="product-grid">
								<div class="product-photo">
                                <?php $productImage = $list_product->getImage($_product, $image); ?>
                                <?php if ($pos != null): ?>
                                    <?php $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"'; ?>
                                <?php endif; ?>
                             
                                    <?php $_productNameStripped = $list_product->stripTags($_product->getName(), null, true); ?>
                                    
										<?php // Product Image ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php echo $productImage->toHtml(); ?>
								</a>
								<div class="addto-links-bottom">
									 <ul class="add-to-links">
										<li>
											 <div class="actions-add-cart">
											 <div class="actions clearfix">
									<div class="action-inner">
                                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                           
                                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                                    <?php if ($showCart): ?>                                                       
                                                            <?php if ($_product->isSaleable()): ?>
                                                                <?php $postParams = $list_product->getAddToCartPostParams($_product); ?>
                                                                <form data-role="tocart-form"
                                                                      action="<?php echo $postParams['action']; ?>"
                                                                      method="post">
                                                                    <input type="hidden" name="product"
                                                                           value="<?php echo $postParams['data']['product']; ?>">
                                                                    <input type="hidden"
                                                                           name="<?php echo \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                           value="<?php echo $postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                                    <?php echo $list_product->getBlockHtml('formkey') ?>
                                                                    <button type="submit"
                                                                            title="<?php echo $list_product->escapeHtml(__('Add to Cart')); ?>"
                                                                            class="action tocart primary"> 
																		<span><?php echo __('Add to Cart') ?> </span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($_product->getIsSalable()): ?>
                                                                    <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                            echo __('In stock') ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                                            echo __('Out of stock') ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        
                                                    <?php endif; ?>
                                                </div>
                                            
                                        <?php endif; ?>
                                   
                                    
                                    </div>
                                    </div>
                                    </div>
                                
										
										</li>
									 
									 </ul>
								
								</div>
								
								</div>
								<div class="product-info">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<strong class="product name product-item-name">
									<a class="product-item-link"
									   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</strong>
								 <?php echo $showReview ? $list_product->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
								<?php echo $list_product->getProductPrice($_product); ?>
								
								</div>
                                       
										
								
								
								 <?php //echo $showReview ? $list_product->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
								<div class="product-ratting"> 
								
								 </div>
								
                            </div>
                            <?php echo ($iterator == count($collection) + 1) ? '</li>' : '' ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php } ?>
            </ul>
			</div>
        </div>
    <?php endif; ?>
	
    <script>
        // define is used to register a module in require js
        /* require(['jquery', 'slick'], function ($) {
            //your js code here
            jQuery(function () {
                if (!$('.regular').hasClass('slick-initialized')) {
                    $(".regular").slick({
                        dots: false,
                        infinite: true,
                        slidesToShow: 6,
                        slidesToScroll: 1,
                        arrows: true,
                        autoplay: false,
                        draggable: true,
                        speed: 300,
                        responsive: [
                            {
                                breakpoint: 1199,
                                settings: {
                                    slidesToShow: 4
                                }
                            },
                            {
                                breakpoint: 991,
                                settings: {
                                    slidesToShow: 3
                                }
                            },
                            {
                                breakpoint: 639,
                                settings: {
                                    slidesToShow: 2
                                }
                            },
                            {
                                breakpoint: 360,
                                settings: {
                                    slidesToShow: 2
                                }
                            }
                        ]
                    });
                    $(".lazy").slick({
                        lazyLoad: 'ondemand', // ondemand progressive anticipated
                        infinite: true
                    });
                }
            });
        }); */
    </script>
	<script>
				require([
					'jquery',
					'mage/mage',
					'rokanthemes/owl'
				], function ($) {
					'use strict';

					jQuery(".rokan-featuredproduct .owl").owlCarousel({
						autoPlay : false,
						items : 4,
						itemsDesktop : [1199,4],
						itemsDesktopSmall : [980,3],
						itemsTablet: [768,2],
						itemsMobile : [479,1],
						slideSpeed : 500,
						paginationSpeed : 500,
						rewindSpeed : 500,
						navigation : true,
						stopOnHover : true,
						pagination :false,
						scrollPerPage:true,
					});
				});
			</script>
<?php endif; ?>