<div class="top-content-home">
	<div class="section-element new_product">
		<div class="container dasdadasd">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Newproduct\Block\Newproduct')->setTemplate('Rokanthemes_Newproduct::newproduct.phtml')->toHtml();?> 
			
		</div>
	</div>
	<div class="section-element banner_static">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_static')->toHtml();?>
		</div>
	</div>
	<div class="section-element banner_middle">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_middle')->toHtml();?>
	</div>
	<div class="section-element group-product">
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-xs-12">
					
					<?php echo $block->getLayout()->createBlock('RLTSquare\BestSeller\Block\Product\GridProduct')->setTemplate('RLTSquare_BestSeller::viewed.phtml')->toHtml();?>
				</div>
				
			</div>
		</div>
	</div>
		
		

	<div class="section-element featured_product">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Featuredpro\Block\Featured')->setTemplate('Rokanthemes_Featuredpro::featured.phtml')->toHtml();?> 
			
		</div>
	</div>

	<div class="section-element section-newsletter">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('Magento_Newsletter::subscribe.phtml')->toHtml();?> 
		</div>
	</div>

	<div class="section-element section-services">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shipping_support')->toHtml();?> 
		</div>
	</div>

	<div class="section-element box-blog">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
		</div>
	</div>
	<div class="section-brands">
		<div class="container">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('brand-logo')->toHtml(); ?>
		</div>
	</div>
	<div class="section-element Instagram_static">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Instagram_static')->toHtml();?>
		</div>
	</div>
</div>
